[package]
name = "sc-common-cryptolib"
version = "0.1.0"
authors = ["DanieleDiBenedetto <daniele@horizenlabs.io>"]
edition = "2018"

[dependencies]
common-api = { path = "../api"}

[lib]
name = "sc_common"
path = "src/lib.rs"
crate_type = ["cdylib"]